# Generated by Django 5.2.6 on 2026-01-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLShortener',
        ),
    ]
